# nfpm example config file
#
# check https://nfpm.goreleaser.com/configuration for detailed usage
#
name: "hades-agent"
arch: arm64
platform: "linux"
epoch: 3
version: v1.1.0
release: 1
section: "default"
priority: "extra"
maintainer: "chriskali <chriskali@protonmail.com>"
description: |
  HIDS hades-agent
vendor: "theSecHunter"
homepage: "https://github.com/chriskaliX"
license: "MIT"
changelog: "changelog.yaml"
contents:
  - src: ./hades-agent.service
    dst: /etc/hades/hades-agent.service
    file_info:
      mode: 0600
      owner: root
      group: root
  - src: ./hades-agent
    dst: /etc/hades/hades-agent
    file_info:
      mode: 0700
      owner: root
      group: root
  - src: ./scripts/hades-agent.sysvinit
    dst: /etc/hades/hades-agent.sysvinit
    file_info:
      mode: 0700
      owner: root
      group: root
  - src: ./hadesctl
    dst: /etc/hades/hadesctl
    file_info:
      mode: 0700
      owner: root
      group: root
# -- in elkeid, there is a ctl for this
scripts:
  preremove: ./scripts/postremove.sh
  preinstall: ./scripts/preinstall.sh
  postremove: ./scripts/postremove.sh
  postinstall: ./scripts/postinstall.sh
